import React from "react";
import StoreTable from "./_Component/StoreTable";

export const metadata = {
  title: "Store Management",
  description: "Generated by create next app",
};

function page() {
  return (
    <div>
      <StoreTable />
    </div>
  );
}

export default page;
