import React from "react";
import PushNOtificationTable from "./PushNOtificationTable";
export const metadata = {
  title: "Push Notifications",
  description: "Generated by create next app",
};

export default function PushNOtificationContainer() {
  return (
    <div>
      <PushNOtificationTable />
    </div>
  );
}
