import React from "react";
import CuponsTable from "./_Component/CuponsTable";

export const metadata = {
  title: "Coupon Management",
  description: "Generated by create next app",
};

function page() {
  return (
    <div>
      <CuponsTable />
    </div>
  );
}

export default page;
