import React from "react";
import ManageEditorAndViewer from "./_Component/ManageEditorAndViewer";

export const metadata = {
  title: "Manage Editor & Viewer",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
      <ManageEditorAndViewer />
    </div>
  );
}
