import React from "react";
import CuponTrakingContainer from "./_Component/CuponTrakingContainer";

export const metadata = {
  title: "Coupon Tracking",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <CuponTrakingContainer />
    </div>
  );
};

export default page;
