import BannerPage from "./_Component/BannerPage";

export const metadata = {
  title: "Add Banner",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <BannerPage />
    </div>
  );
};

export default page;
