import React from "react";
import PushNOtificationContainer from "./_Component/PushNOtificationContainer";

export const metadata = {
  title: "Push Notifications",
  description: "Generated by create next app",
};

function page() {
  return (
    <div>
      <PushNOtificationContainer />
    </div>
  );
}

export default page;
